### ISSUE TITLE
SSCrawler Trigger Permissions Bug

### ISSUE THREAD

**Issue by TyReed12** [ActoKids/web-crawler#16]
Cannot create trigger for sscrawler due to lack of permissions.

**Comment by TyReed12** [comment]
![permissionserror](https://user-images.githubusercontent.com/34496119/53754803-dfe00700-3e69-11e9-90c7-6c106ad18c64.JPG)

**Comment by bmenaz** [comment]
I have added the permission, it should fix the issue, could you check it and let me know. Thanks.

**Comment by TyReed12** [comment]
I was able to create the trigger successfully. Thank you!
