### ISSUE TITLE
Verify Data Models Match

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/web-crawler#20]
I had a quick peek at the crawler 1box DynamoDB with Ryan over the weekend and it looked like there may be some discrepancies between the API and Crawler data models. Here is a [link](https://github.com/ActoKids/api/wiki/Data-Model) to our data model. Please compare and make sure we are on the same page.

**Comment by MikeJLeon** [comment]
I have finished this, Thank you for catching this Alex.

@rberry206 When you finish please go ahead and close this issue.

**Comment by rberry206** [comment]
I finished the Google variable names. Closing the issue @MikeJLeon @Enshaedn @erikNeville .
