### ISSUE TITLE
Crawler Production Trigger Permissions Bug

### ISSUE THREAD

**Issue by TyReed12** [ActoKids/web-crawler#21]
Receiving error message when creating a trigger in CloudWatch for GoogleCalCrawler.

**Comment by TyReed12** [comment]
![newpermissionserror](https://user-images.githubusercontent.com/34496119/54309769-08fd4780-458e-11e9-9452-3dc07322bc7a.JPG)

**Comment by bmenaz** [comment]
Hi Tyler, I have looked into your error and made some changes into the policy and added a permission. Could you check it and let me know if it has been resolved.

**Comment by TyReed12** [comment]
Thanks! It seems to be resolved. Closing issue.
